[project]
name = "cql-agent"
version = "0.1.0"
description = "AI Agent for Home Repairs"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "duckduckgo-search>=8.1.1",
    "langchain>=0.3.27",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.3.31",
    "langchain-ollama>=0.3.10",
    "pydantic>=2.12.2",
    "pypdf>=6.1.1",
    "flask>=3.0.0",
    "flask-cors>=5.0.0",
    "flask-restx>=1.3.0",
    "requests>=2.32.0",
    "gunicorn>=21.2.0",
]
