name: on_push_to_main

on:
  push:
    branches:
      - main

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv sync

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        working-directory: ./web
        run: pnpm install

      - name: Run frontend unit tests
        working-directory: ./web
        run: pnpm test -- --coverage
      
      - name: Run linter (flake8)
        run: uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Run linter (pylint)
        run: uv run pylint **/*.py --fail-under=8.0
        continue-on-error: true
      
      - name: Run unit tests
        run: uv run pytest -v